site_name: 'Late Night Linux - Discoveries'
site_description: 'This site details all discoveries mentioned during episodes of Late Night Linux'
site_author: 'Matt Holder'
site_dir: '../docs'
site_url: 'https://mattmole.co.uk/LNL-Discoveries'
#extra_javascript: [extra.js]
#extra_css: [extra.css]
repo_url: 'https://github.com/mattmole/LNL-Discoveries'
repo_name: 'GitHub'
edit_uri_template: 'blob/main/LateNightLinuxMkDocsV2/docs/{path}'
plugins:
#    - offline
    - awesome-pages
    - search
    - rss:
        match_path: "rss/.*"
        abstract_chars_count: -1
        length: -1
        abstract_delimiter: <!-- more -->
        date_from_meta:
            as_creation: "date"
            as_update: "date"
            datetime_format: "%d/%m/%Y %H:%M:%S"
            default_timezone: Europe/London
            default_time: "09:30"
#    - git-revision-date-localized:
#        enable_creation_date: true
theme:
    features:
      - navigation.tabs
      - search.highlight
      - search.share
    name: material
    palette:
        primary: black
        scheme: slate
    logo: assets/header-600.png

